### ISSUE TITLE
Template customization

### ISSUE THREAD

**Issue by PrestaShark** [getdatakick/revws#107]
Without doubt - module is perfect designed and insanely well coded. One of the best i have ever seen from years!

But its very hard to change template or its view. For example - how to change #ff1744 color of pink inputs? 

Also how to change something in all reviews page? All changes to the template are overwrite by loaded front.js file. It's real anoying and uneseceary

**Comment by getdatakick** [comment]
This is intentional. This module is not made for poweruser / developers. It's designed for common merchant that have limited html/css knowledge.

Most prestashop users are accustomed to modifying template. This indeed does not work here, as anything rendered by template is overwritten by javascript code. You are saying it's unnecessary and annoying. But in fact this is the reason why this module can achieve its interactiveness. 

If I dropped this front-end javascript rendering from the module, than the result would be normal, boring, non-interactive module. 

Moreover, I don't see any reason to do this. If you want to modify design, there's CSS for that. There's no reason to modify template to change how things looks. Template should only provide structure, how this structure is presented is up to CSS layer. There are a LOT OF css classes you can target to tweak every design aspect of this theme.
